live_config_reload = true

[font]
size = 15.5

offset = { x = 1, y = 3 }

builtin_box_drawing = true

normal = { family = "Operator Mono", style = "Medium Italic" }

[window]

decorations = "Full" #"Transparent"

opacity = 0.9

padding = { x = 10, y = 10 }

# Default colors
[colors.primary]
background = '#292d3e'
foreground = '#d0d0d0'

# Normal colors
[colors.normal]
black   = '#292d3e'
red     = '#f07178'
green   = '#c3e88d'
yellow  = '#ffcb6b'
blue    = '#82aaff'
magenta = '#c792ea'
cyan    = '#89ddff'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#434758'
red     = '#ff8b92'
green   = '#ddffa7'
yellow  = '#ffe585'
blue    = '#9cc4ff'
magenta = '#e1acff'
cyan    = '#a3f7ff'
white   = '#ffffff'

