live_config_reload = true

import = [
    "~/developer/dotfiles/alacritty/catppuccin-mocha.toml"
]
[font]
size = 12

offset = { x = 1, y = 3 }

builtin_box_drawing = true

normal = { family = "JetBrainsMono Nerd Font" }

[window]

#decorations = "Transparent" #"Transparent"

opacity = 1.0

padding = { x = 10, y = 10 }

