live_config_reload = true

[font]
size = 15.5

builtin_box_drawing = true

#[font.bold]
#family = "Operator Mono Bold"
#style = "Bold"

#[font.bold_italic]
#family = "Operator Mono"
#style = "Bold Italic"

[font.italic]
family = "Operator Mono"
style = "Italic"

#[font.normal]
#family = "Operator Mono Bold"
#style = "regular"

[window]

decorations = "Transparent"

opacity = 0.9

padding = { x = 10, y = 30 }

# Default colors
[colors.primary]
background = '#292d3e'
foreground = '#d0d0d0'

# Normal colors
[colors.normal]
black   = '#292d3e'
red     = '#f07178'
green   = '#c3e88d'
yellow  = '#ffcb6b'
blue    = '#82aaff'
magenta = '#c792ea'
cyan    = '#89ddff'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#434758'
red     = '#ff8b92'
green   = '#ddffa7'
yellow  = '#ffe585'
blue    = '#9cc4ff'
magenta = '#e1acff'
cyan    = '#a3f7ff'
white   = '#ffffff'

