cursor            #ffb5a1
cursor_text_color #561f10

foreground            #f1dfda
background            #140c0a
selection_foreground  #442a23
selection_background  #e7bdb2
url_color             #e7bdb2

#: black 000000 767676
color0  #1a110f
color8  #3d3230
#: red cc0403 f2201f
color1  #000000
color9  #1a1a1a
#: green 19cb00 23fd00
color2  #e7bdb2
color10 #ffdbd1
#: yellow cecb00 fffd00
color3  #d9c58d
color11 #f6e1a6
#: blue 0d73cc 1a8fff
color4  #723523
color12 #ffb5a1
#: magenta cb1ed1 fd28ff
color5  #5d4038
color13 #e7bdb2
#: cyan 0dcdcd 14ffff
color6  #534619
color14 #d9c58d
#: white dddddd ffffff
color7  #d8c2bc
color15 #f1dfda

mark1_foreground #3a0b01
mark1_background #ffdbd1
mark2_foreground #2c150f
mark2_background #ffdbd1
mark3_foreground #231b00
mark3_background #f6e1a6

active_tab_foreground #561f10
active_tab_background #ffb5a1
inactive_tab_foreground #ffdbd1
inactive_tab_background #723523

active_border_color #ffb5a1
inactive_border_color #561f10
# bell_border_color #ff5a00
