cursor            #ffb2b9
cursor_text_color #561d26

foreground            #f0dedf
background            #140c0d
selection_foreground  #44292c
selection_background  #e5bdbf
url_color             #e5bdbf

#: black 000000 767676
color0  #1a1112
color8  #3d3233
#: red cc0403 f2201f
color1  #9e4d3a
color9  #d9a498
#: green 19cb00 23fd00
color2  #e5bdbf
color10 #ffdadc
#: yellow cecb00 fffd00
color3  #e8c08e
color11 #ffddb6
#: blue 0d73cc 1a8fff
color4  #72333b
color12 #ffb2b9
#: magenta cb1ed1 fd28ff
color5  #5c3f42
color13 #e5bdbf
#: cyan 0dcdcd 14ffff
color6  #5d411b
color14 #e8c08e
#: white dddddd ffffff
color7  #d7c1c2
color15 #f0dedf

mark1_foreground #3b0712
mark1_background #ffdadc
mark2_foreground #2c1517
mark2_background #ffdadc
mark3_foreground #2a1800
mark3_background #ffddb6

active_tab_foreground #561d26
active_tab_background #ffb2b9
inactive_tab_foreground #ffdadc
inactive_tab_background #72333b

active_border_color #ffb2b9
inactive_border_color #561d26
# bell_border_color #ff5a00
