#!/usr/bin/env bash
DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.tmux
rm $HOME/.tmux.conf
ln -s $DOTFILES/tmux/.tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.config/tmux
ln -s $DOTFILES/tmux $HOME/.config/tmux

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zshrc/zshrc.conf $HOME/.zshrc

rm -rf $HOME/.vimrc
ln -s $DOTFILES/vimrc/.vimrc $HOME/.vimrc

rm -rf $HOME/.alacritty.toml
ln -s $DOTFILES/alacritty/alacritty.toml $HOME/.alacritty.toml

rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty

rm -rf $HOME/.aerospace.toml
ln -s $DOTFILES/aerospace/aerospace.toml $HOME/.aerospace.toml

rm -rf $HOME/.hushlogin
touch $HOME/.hushlogin

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.warp
ln -s $DOTFILES/warp $HOME/.warp

rm -rf $HOME/.config/starship.toml
ln -s $DOTFILES/starship/starship.toml $HOME/.config/starship.toml

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t
