#!/usr/bin/env bash
DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zshrc/zshrc.conf $HOME/.zshrc

rm -rf $HOME/.vimrc
ln -s $DOTFILES/vimrc/.vimrc $HOME/.vimrc

rm -rf $HOME/.alacritty.toml
ln -s $DOTFILES/alacritty/alacritty.toml $HOME/.alacritty.toml

rm -rf $HOME/.hushlogin
touch $HOME/.hushlogin

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.warp
ln -s $DOTFILES/warp $HOME/.warp

