//
// Material 3 colour scheme.
//
// GENERATED BY MATUGEN - do not edit. Edit matugen/templates/quickshell-scheme.qml
// instead, then re-run `matugen image <wallpaper>`.
//
// Consumed by services/Colours.qml, which adds the layering/transparency helpers.
// Quickshell hot-reloads on file change, so a new wallpaper retints the bar live.
//
import QtQuick

QtObject {
    readonly property color m3background: "#fdfaec"
    readonly property color m3error: "#ba1a1a"
    readonly property color m3errorContainer: "#ffdad6"
    readonly property color m3inverseOnSurface: "#f4f1e4"
    readonly property color m3inversePrimary: "#c8cc78"
    readonly property color m3inverseSurface: "#313128"
    readonly property color m3onBackground: "#1c1c14"
    readonly property color m3onError: "#ffffff"
    readonly property color m3onErrorContainer: "#410002"
    readonly property color m3onPrimary: "#ffffff"
    readonly property color m3onPrimaryContainer: "#1c1d00"
    readonly property color m3onPrimaryFixed: "#1c1d00"
    readonly property color m3onPrimaryFixedVariant: "#474a01"
    readonly property color m3onSecondary: "#ffffff"
    readonly property color m3onSecondaryContainer: "#1c1d06"
    readonly property color m3onSecondaryFixed: "#1c1d06"
    readonly property color m3onSecondaryFixedVariant: "#47482d"
    readonly property color m3onSurface: "#1c1c14"
    readonly property color m3onSurfaceVariant: "#48473b"
    readonly property color m3onTertiary: "#ffffff"
    readonly property color m3onTertiaryContainer: "#002118"
    readonly property color m3onTertiaryFixed: "#002118"
    readonly property color m3onTertiaryFixedVariant: "#244e41"
    readonly property color m3outline: "#797869"
    readonly property color m3outlineVariant: "#c9c7b6"
    readonly property color m3primary: "#5f621a"
    readonly property color m3primaryContainer: "#e5e891"
    readonly property color m3primaryFixed: "#e5e891"
    readonly property color m3primaryFixedDim: "#c8cc78"
    readonly property color m3scrim: "#000000"
    readonly property color m3secondary: "#5f6043"
    readonly property color m3secondaryContainer: "#e5e5c0"
    readonly property color m3secondaryFixed: "#e5e5c0"
    readonly property color m3secondaryFixedDim: "#c9c9a5"
    readonly property color m3shadow: "#000000"
    readonly property color m3surface: "#fdfaec"
    readonly property color m3surfaceBright: "#fdfaec"
    readonly property color m3surfaceContainer: "#f1eee1"
    readonly property color m3surfaceContainerHigh: "#ebe8db"
    readonly property color m3surfaceContainerHighest: "#e5e3d6"
    readonly property color m3surfaceContainerLow: "#f7f4e6"
    readonly property color m3surfaceContainerLowest: "#ffffff"
    readonly property color m3surfaceDim: "#dddacd"
    readonly property color m3surfaceTint: "#5f621a"
    readonly property color m3surfaceVariant: "#e5e3d1"
    readonly property color m3tertiary: "#3c6658"
    readonly property color m3tertiaryContainer: "#bfecda"
    readonly property color m3tertiaryFixed: "#bfecda"
    readonly property color m3tertiaryFixedDim: "#a3d0bf"
}
