//
// Material 3 colour scheme.
//
// GENERATED BY MATUGEN - do not edit. Edit matugen/templates/quickshell-scheme.qml
// instead, then re-run `matugen image <wallpaper>`.
//
// Consumed by services/Colours.qml, which adds the layering/transparency helpers.
// Quickshell hot-reloads on file change, so a new wallpaper retints the bar live.
//
// The root type is services/M3Palette.qml rather than a bare QtObject: Colours
// keeps a second instance of the same component as a preview palette, which the
// wallpaper picker fills from a `matugen --dry-run`. The role names live there,
// so this file only assigns to them.
//
M3Palette {
    m3background: "#101418"
    m3error: "#ffb4ab"
    m3errorContainer: "#93000a"
    m3inverseOnSurface: "#2d3135"
    m3inversePrimary: "#2e628c"
    m3inverseSurface: "#e0e2e8"
    m3onBackground: "#e0e2e8"
    m3onError: "#690005"
    m3onErrorContainer: "#ffdad6"
    m3onPrimary: "#003352"
    m3onPrimaryContainer: "#cde5ff"
    m3onPrimaryFixed: "#001d32"
    m3onPrimaryFixedVariant: "#0b4a72"
    m3onSecondary: "#233240"
    m3onSecondaryContainer: "#d5e4f6"
    m3onSecondaryFixed: "#0e1d2a"
    m3onSecondaryFixedVariant: "#3a4857"
    m3onSurface: "#e0e2e8"
    m3onSurfaceVariant: "#c2c7cf"
    m3onTertiary: "#382a49"
    m3onTertiaryContainer: "#eedcff"
    m3onTertiaryFixed: "#221533"
    m3onTertiaryFixedVariant: "#4f4061"
    m3outline: "#8c9198"
    m3outlineVariant: "#42474e"
    m3primary: "#9acbfa"
    m3primaryContainer: "#0b4a72"
    m3primaryFixed: "#cde5ff"
    m3primaryFixedDim: "#9acbfa"
    m3scrim: "#000000"
    m3secondary: "#b9c8da"
    m3secondaryContainer: "#3a4857"
    m3secondaryFixed: "#d5e4f6"
    m3secondaryFixedDim: "#b9c8da"
    m3shadow: "#000000"
    m3surface: "#101418"
    m3surfaceBright: "#36393e"
    m3surfaceContainer: "#1c2024"
    m3surfaceContainerHigh: "#272a2e"
    m3surfaceContainerHighest: "#313539"
    m3surfaceContainerLow: "#181c20"
    m3surfaceContainerLowest: "#0b0f12"
    m3surfaceDim: "#101418"
    m3surfaceTint: "#9acbfa"
    m3surfaceVariant: "#42474e"
    m3tertiary: "#d2bfe7"
    m3tertiaryContainer: "#4f4061"
    m3tertiaryFixed: "#eedcff"
    m3tertiaryFixedDim: "#d2bfe7"

    // Recorded rather than inferred. Colours used to guess the mode back out of
    // the surface luminance, which is also true of the *preview* palette - and a
    // preview that looked light would have dragged the portal key and the GTK3
    // theme with it. Same expansion nvim-colors.vim uses for `set background=`.
    mode: "dark"
}
