//
// Material 3 colour scheme.
//
// GENERATED BY MATUGEN - do not edit. Edit matugen/templates/quickshell-scheme.qml
// instead, then re-run `matugen image <wallpaper>`.
//
// Consumed by services/Colours.qml, which adds the layering/transparency helpers.
// Quickshell hot-reloads on file change, so a new wallpaper retints the bar live.
//
import QtQuick

QtObject {
    readonly property color m3background: "#1a1112"
    readonly property color m3error: "#ffb4ab"
    readonly property color m3errorContainer: "#93000a"
    readonly property color m3inverseOnSurface: "#382e2e"
    readonly property color m3inversePrimary: "#8f4952"
    readonly property color m3inverseSurface: "#f0dedf"
    readonly property color m3onBackground: "#f0dedf"
    readonly property color m3onError: "#690005"
    readonly property color m3onErrorContainer: "#ffdad6"
    readonly property color m3onPrimary: "#561d26"
    readonly property color m3onPrimaryContainer: "#ffdadc"
    readonly property color m3onPrimaryFixed: "#3b0712"
    readonly property color m3onPrimaryFixedVariant: "#72333b"
    readonly property color m3onSecondary: "#44292c"
    readonly property color m3onSecondaryContainer: "#ffdadc"
    readonly property color m3onSecondaryFixed: "#2c1517"
    readonly property color m3onSecondaryFixedVariant: "#5c3f42"
    readonly property color m3onSurface: "#f0dedf"
    readonly property color m3onSurfaceVariant: "#d7c1c2"
    readonly property color m3onTertiary: "#442b06"
    readonly property color m3onTertiaryContainer: "#ffddb6"
    readonly property color m3onTertiaryFixed: "#2a1800"
    readonly property color m3onTertiaryFixedVariant: "#5d411b"
    readonly property color m3outline: "#9f8c8d"
    readonly property color m3outlineVariant: "#524344"
    readonly property color m3primary: "#ffb2b9"
    readonly property color m3primaryContainer: "#72333b"
    readonly property color m3primaryFixed: "#ffdadc"
    readonly property color m3primaryFixedDim: "#ffb2b9"
    readonly property color m3scrim: "#000000"
    readonly property color m3secondary: "#e5bdbf"
    readonly property color m3secondaryContainer: "#5c3f42"
    readonly property color m3secondaryFixed: "#ffdadc"
    readonly property color m3secondaryFixedDim: "#e5bdbf"
    readonly property color m3shadow: "#000000"
    readonly property color m3surface: "#1a1112"
    readonly property color m3surfaceBright: "#413737"
    readonly property color m3surfaceContainer: "#271d1e"
    readonly property color m3surfaceContainerHigh: "#312828"
    readonly property color m3surfaceContainerHighest: "#3d3233"
    readonly property color m3surfaceContainerLow: "#22191a"
    readonly property color m3surfaceContainerLowest: "#140c0d"
    readonly property color m3surfaceDim: "#1a1112"
    readonly property color m3surfaceTint: "#ffb2b9"
    readonly property color m3surfaceVariant: "#524344"
    readonly property color m3tertiary: "#e8c08e"
    readonly property color m3tertiaryContainer: "#5d411b"
    readonly property color m3tertiaryFixed: "#ffddb6"
    readonly property color m3tertiaryFixedDim: "#e8c08e"
}
