$image = /home/jose/developer/dotfiles/wallpapers/Wallpaper Violet Evergarden White And Black.png

$background = rgba(fdfaecff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(f4f1e4ff)

$inverse_primary = rgba(c8cc78ff)

$inverse_surface = rgba(313128ff)

$on_background = rgba(1c1c14ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(1c1d00ff)

$on_primary_fixed = rgba(1c1d00ff)

$on_primary_fixed_variant = rgba(474a01ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(1c1d06ff)

$on_secondary_fixed = rgba(1c1d06ff)

$on_secondary_fixed_variant = rgba(47482dff)

$on_surface = rgba(1c1c14ff)

$on_surface_variant = rgba(48473bff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(002118ff)

$on_tertiary_fixed = rgba(002118ff)

$on_tertiary_fixed_variant = rgba(244e41ff)

$outline = rgba(797869ff)

$outline_variant = rgba(c9c7b6ff)

$primary = rgba(5f621aff)

$primary_container = rgba(e5e891ff)

$primary_fixed = rgba(e5e891ff)

$primary_fixed_dim = rgba(c8cc78ff)

$scrim = rgba(000000ff)

$secondary = rgba(5f6043ff)

$secondary_container = rgba(e5e5c0ff)

$secondary_fixed = rgba(e5e5c0ff)

$secondary_fixed_dim = rgba(c9c9a5ff)

$shadow = rgba(000000ff)

$source_color = rgba(ece9deff)

$surface = rgba(fdfaecff)

$surface_bright = rgba(fdfaecff)

$surface_container = rgba(f1eee1ff)

$surface_container_high = rgba(ebe8dbff)

$surface_container_highest = rgba(e5e3d6ff)

$surface_container_low = rgba(f7f4e6ff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(dddacdff)

$surface_tint = rgba(5f621aff)

$surface_variant = rgba(e5e3d1ff)

$tertiary = rgba(3c6658ff)

$tertiary_container = rgba(bfecdaff)

$tertiary_fixed = rgba(bfecdaff)

$tertiary_fixed_dim = rgba(a3d0bfff)

