#!/usr/bin/env python3
import os
import subprocess
from datetime import datetime

BASE_DIR = "/home/jose/developer/catppuccin-wallpapers/landscapes/"
WALLPAPERS = {
    "morning": f"{BASE_DIR}tropic_island_morning.jpg",
    "day": f"{BASE_DIR}tropic_island_day.jpg",
    "evening": f"{BASE_DIR}tropic_island_evening.jpg",
    "night": f"{BASE_DIR}tropic_island_night.jpg",
}

hour = datetime.now().hour

if hour >= 6 and hour < 12:
    wallpaper = WALLPAPERS["morning"]
elif hour >= 12 and hour < 18:
    wallpaper = WALLPAPERS["day"]
elif hour >= 18 and hour < 21:
    wallpaper = WALLPAPERS["evening"]
elif hour >= 21 or hour < 6:
    wallpaper = WALLPAPERS["night"]

subprocess.run(["/usr/bin/hyprctl", "hyprpaper", "preload", wallpaper])
subprocess.run(["/usr/bin/hyprctl", "hyprpaper", "wallpaper", f",{wallpaper}"])
