#!/usr/bin/env python3
import os
import subprocess
from datetime import datetime

# BASE_DIR = "/home/jose/developer/catppuccin-wallpapers/landscapes/"
# WALLPAPERS = {
#     "morning": f"{BASE_DIR}tropic_island_morning.jpg",
#     "day": f"{BASE_DIR}tropic_island_day.jpg",
#     "evening": f"{BASE_DIR}tropic_island_evening.jpg",
#     "night": f"{BASE_DIR}tropic_island_night.jpg",
# }

# hour = datetime.now().hour

# if hour >= 5 and hour < 9:
#     wallpaper = WALLPAPERS["morning"]
# elif hour >= 9 and hour < 18:
#     wallpaper = WALLPAPERS["day"]
# elif hour >= 18 and hour < 21:
#     wallpaper = WALLPAPERS["evening"]
# elif hour >= 21 or hour < 5:
#     wallpaper = WALLPAPERS["night"]
# subprocess.run(["/usr/bin/hyprctl", "hyprpaper", "preload", wallpaper])
# subprocess.run(["/usr/bin/hyprctl", "hyprpaper", "wallpaper", f",{wallpaper}"])

# wallpaper = "/home/jose/developer/dotfiles/wallpapers/Rain-World-cats-video-games-Video-Game-Creatures-2168351.png"
# wallpaper = "/home/jose/developer/dotfiles/wallpapers/lofi-coffee-shop-night-thumb.jpg"
# subprocess.run(["/usr/bin/hyprctl", "hyprpaper", "preload", wallpaper])
# subprocess.run(["/usr/bin/hyprctl", "hyprpaper", "wallpaper", f",{wallpaper}"])
