#!/usr/bin/env bash

# credit to The Primeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/developer -maxdepth 1 -mindepth 1 -type d`
    items+=`find ~/Developer -maxdepth 1 - mindepth 1 -type d`
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected | sed 's/\./_/g'`

tmux switch-client -t =$dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname

