//
// Material 3 colour scheme.
//
// GENERATED BY MATUGEN - do not edit. Edit matugen/templates/quickshell-scheme.qml
// instead, then re-run `matugen image <wallpaper>`.
//
// Consumed by services/Colours.qml, which adds the layering/transparency helpers.
// Quickshell hot-reloads on file change, so a new wallpaper retints the bar live.
//
import QtQuick

QtObject {
    readonly property color m3background: "{{colors.background.default.hex}}"
    readonly property color m3error: "{{colors.error.default.hex}}"
    readonly property color m3errorContainer: "{{colors.error_container.default.hex}}"
    readonly property color m3inverseOnSurface: "{{colors.inverse_on_surface.default.hex}}"
    readonly property color m3inversePrimary: "{{colors.inverse_primary.default.hex}}"
    readonly property color m3inverseSurface: "{{colors.inverse_surface.default.hex}}"
    readonly property color m3onBackground: "{{colors.on_background.default.hex}}"
    readonly property color m3onError: "{{colors.on_error.default.hex}}"
    readonly property color m3onErrorContainer: "{{colors.on_error_container.default.hex}}"
    readonly property color m3onPrimary: "{{colors.on_primary.default.hex}}"
    readonly property color m3onPrimaryContainer: "{{colors.on_primary_container.default.hex}}"
    readonly property color m3onPrimaryFixed: "{{colors.on_primary_fixed.default.hex}}"
    readonly property color m3onPrimaryFixedVariant: "{{colors.on_primary_fixed_variant.default.hex}}"
    readonly property color m3onSecondary: "{{colors.on_secondary.default.hex}}"
    readonly property color m3onSecondaryContainer: "{{colors.on_secondary_container.default.hex}}"
    readonly property color m3onSecondaryFixed: "{{colors.on_secondary_fixed.default.hex}}"
    readonly property color m3onSecondaryFixedVariant: "{{colors.on_secondary_fixed_variant.default.hex}}"
    readonly property color m3onSurface: "{{colors.on_surface.default.hex}}"
    readonly property color m3onSurfaceVariant: "{{colors.on_surface_variant.default.hex}}"
    readonly property color m3onTertiary: "{{colors.on_tertiary.default.hex}}"
    readonly property color m3onTertiaryContainer: "{{colors.on_tertiary_container.default.hex}}"
    readonly property color m3onTertiaryFixed: "{{colors.on_tertiary_fixed.default.hex}}"
    readonly property color m3onTertiaryFixedVariant: "{{colors.on_tertiary_fixed_variant.default.hex}}"
    readonly property color m3outline: "{{colors.outline.default.hex}}"
    readonly property color m3outlineVariant: "{{colors.outline_variant.default.hex}}"
    readonly property color m3primary: "{{colors.primary.default.hex}}"
    readonly property color m3primaryContainer: "{{colors.primary_container.default.hex}}"
    readonly property color m3primaryFixed: "{{colors.primary_fixed.default.hex}}"
    readonly property color m3primaryFixedDim: "{{colors.primary_fixed_dim.default.hex}}"
    readonly property color m3scrim: "{{colors.scrim.default.hex}}"
    readonly property color m3secondary: "{{colors.secondary.default.hex}}"
    readonly property color m3secondaryContainer: "{{colors.secondary_container.default.hex}}"
    readonly property color m3secondaryFixed: "{{colors.secondary_fixed.default.hex}}"
    readonly property color m3secondaryFixedDim: "{{colors.secondary_fixed_dim.default.hex}}"
    readonly property color m3shadow: "{{colors.shadow.default.hex}}"
    readonly property color m3surface: "{{colors.surface.default.hex}}"
    readonly property color m3surfaceBright: "{{colors.surface_bright.default.hex}}"
    readonly property color m3surfaceContainer: "{{colors.surface_container.default.hex}}"
    readonly property color m3surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color m3surfaceContainerHighest: "{{colors.surface_container_highest.default.hex}}"
    readonly property color m3surfaceContainerLow: "{{colors.surface_container_low.default.hex}}"
    readonly property color m3surfaceContainerLowest: "{{colors.surface_container_lowest.default.hex}}"
    readonly property color m3surfaceDim: "{{colors.surface_dim.default.hex}}"
    readonly property color m3surfaceTint: "{{colors.surface_tint.default.hex}}"
    readonly property color m3surfaceVariant: "{{colors.surface_variant.default.hex}}"
    readonly property color m3tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color m3tertiaryContainer: "{{colors.tertiary_container.default.hex}}"
    readonly property color m3tertiaryFixed: "{{colors.tertiary_fixed.default.hex}}"
    readonly property color m3tertiaryFixedDim: "{{colors.tertiary_fixed_dim.default.hex}}"
}
